import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { Action,CommentSection,PhotoCarousel,availabilityLabel } from "@/components/community-ui";
import { CommerceSettings,MakeOffer } from "@/components/collection-offers";
import { getCurrentCollector } from "@/lib/collector-auth";
import { getPiece,getShelves } from "@/lib/community";
import { expireCollectionOffers } from "@/lib/collection-offers";
export const dynamic='force-dynamic';
export const metadata={title:'Collection piece',robots:{index:false,follow:true}};
export default async function PiecePage({params}:{params:Promise<{id:string}>}){const{id}=await params,c=await getCurrentCollector(),viewer=c?.user.id??null;await expireCollectionOffers();const piece=await getPiece(id,viewer);if(!piece)notFound();const owner=piece.ownerId===viewer,shelves=(await getShelves(piece.ownerId,viewer)).filter(s=>s.itemId===piece.id);return <><SiteHeader/><main id="main-content" className="piece-detail shell"><nav className="breadcrumbs"><Link href={owner?'/collection':`/collectors/${piece.handle}`}>{owner?'My Collection':`${piece.displayName}’s collection`}</Link><span>/</span><span>{piece.title}</span></nav><div className="piece-detail-layout"><PhotoCarousel photos={JSON.parse(piece.photos)} alt={`${piece.displayName}’s ${piece.title}`}/><section><p className="eyebrow">{piece.scale} · {piece.maker}</p><h1>{piece.title}</h1><Link href={`/collectors/${piece.handle}`}>Owned by {piece.displayName}</Link><p className="availability">{availabilityLabel[piece.availability]}</p>{owner&&<p className="privacy-label">{piece.visibility==='private'?'Private — only you':'Public showcase'}</p>}<p>{piece.story}</p>{piece.condition&&<p>Condition: {piece.condition}</p>}<p>{shelves.map(s=>s.name).join(' · ')}</p>{piece.catalogId?<p><Link href={`/models/${piece.catalogId}`}>Exact catalog release</Link></p>:<p>Personal item · catalog identity unconfirmed</p>}{!owner&&piece.availability==='open_to_offers'&&<MakeOffer piece={piece}/>} {!owner&&piece.availability==='for_sale'&&piece.listingSlug&&<Link className="button dark" href={`/products/${piece.listingSlug}`}>View listing</Link>}{piece.availability==='reserved'&&<p>This piece is pending payment. New offers and purchases are unavailable.</p>}{piece.availability==='previously_owned'&&<p>Historical showcase. This piece is excluded from the current collection.</p>}{piece.catalogId&&<div className="community-buttons"><Action payload={{action:'wishlist',catalogId:piece.catalogId}}>Add model to wishlist</Action><Link href={`/models/${piece.catalogId}`}>Find this model from other sellers</Link></div>}{!owner&&<Link href={`/messages?collector=${piece.ownerId}&item=${piece.id}`}>Message about this piece</Link>}{owner&&<><Link href={`/collection?edit=${piece.id}`}>Edit piece</Link><CommerceSettings piece={piece}/><details><summary>Private purchase records</summary><p>{piece.purchaseCost||'No purchase cost recorded'}</p><p>{piece.privateNotes||'No private notes'}</p></details></>}</section></div><CommentSection itemId={id} enabled={Boolean(piece.commentsEnabled)}/></main></>;}
