import { requireAdminApi } from "@/lib/admin-auth";
import { one,required,rows,run,text } from "@/lib/community";
import { readJsonObject,routeError } from "@/lib/http";
import { ValidationError } from "@/lib/validation";
export async function GET(){const a=await requireAdminApi();if(a instanceof Response)return a;return Response.json({reports:await rows("SELECT * FROM community_reports ORDER BY created_at DESC LIMIT 200"),exceptions:await rows("SELECT * FROM community_payment_exceptions WHERE status='open' ORDER BY created_at"),editorial:await one("SELECT * FROM community_editorial ORDER BY created_at DESC LIMIT 1")},{headers:{'Cache-Control':'private, no-store'}});}
export async function POST(request:Request){try{const a=await requireAdminApi();if(a instanceof Response)return a;const p=await readJsonObject(request);if(p.action==='editorial'){await run('INSERT INTO community_editorial (id,title,body,topic,spotlight_id,author,created_at) VALUES (?,?,?,?,?,?,?)',crypto.randomUUID(),required(p.title,'Theme title'),required(p.body,'Theme description',2000),required(p.topic,'Topic',80),text(p.spotlightId)||null,required(p.author,'Public curator name',100),Date.now());return Response.json({ok:true});}
  const report=await one<{target_type:string;target_id:string}>('SELECT * FROM community_reports WHERE id=?',required(p.id,'Report'));if(!report)throw new ValidationError('Report unavailable.');const reason=required(p.resolution,'Moderation reason',2000);
  if(p.action==='remove'){if(report.target_type==='post')await run("UPDATE community_posts SET status='removed' WHERE id=?",report.target_id);else if(report.target_type==='comment')await run("UPDATE community_comments SET status='removed' WHERE id=?",report.target_id);else if(report.target_type==='collector')await run('UPDATE community_settings SET published=0 WHERE user_id=?',report.target_id);else throw new ValidationError('Use the support workflow for private conversation reports.');}else if(p.action!=='dismiss')throw new ValidationError('Unknown moderation action.');
  await run("UPDATE community_reports SET status='resolved',reviewed_by=?,resolution=? WHERE id=?",a.email,reason,String(p.id));return Response.json({ok:true});}catch(e){return routeError(e);}}
