"use client";
import Link from "next/link";
import { useRouter, useSearchParams, usePathname } from "next/navigation";
import type { Piece } from "@/lib/community";
import { PieceCard, SubmitForm, communityRequest } from "./community-ui";
import { CollectionPieceForm } from "./collection-piece-form";
import { ContextualHelp } from "./contextual-help";
import type { CollectionSellingOptions } from "@/lib/collection-offers";
type Shelf={id:string;name:string;itemId:string};
export function CollectionGrid({items,shelves,owner=false}:{items:Piece[];shelves:Shelf[];owner?:boolean}){
  const params=useSearchParams(),router=useRouter(),path=usePathname();
  const scale=params.get('scale')||'',maker=params.get('maker')||'',carMake=params.get('carMake')||'',availability=params.get('availability')||'',shelf=params.get('shelf')||'';
  const filter=(key:string,value:string)=>{const q=new URLSearchParams(params.toString());if(value)q.set(key,value);else q.delete(key);router.replace(path+'?'+q.toString(),{scroll:false});};
  const setScale=(v:string)=>filter('scale',v),setMaker=(v:string)=>filter('maker',v),setCarMake=(v:string)=>filter('carMake',v),setAvailability=(v:string)=>filter('availability',v),setShelf=(v:string)=>filter('shelf',v);
  const unique=[...new Map(shelves.map(s=>[s.id,s])).values()];const filtered=items.filter(i=>(!scale||i.scale===scale)&&(!maker||i.maker===maker)&&(!carMake||i.carMake===carMake)&&(!availability||i.availability===availability)&&(!shelf||shelves.some(s=>s.id===shelf&&s.itemId===i.id)));
  return <><nav className="shelf-tabs" aria-label="Shelves"><button type="button" aria-pressed={!shelf} onClick={()=>setShelf('')}>All pieces</button>{unique.map(s=><button key={s.id} type="button" aria-pressed={shelf===s.id} onClick={()=>setShelf(s.id)}>{s.name}</button>)}</nav><details className="collection-filters"><summary>Filter collection</summary><div>{([['Scale',scale,setScale,items.map(i=>i.scale)],['Manufacturer',maker,setMaker,items.map(i=>i.maker)],['Car make',carMake,setCarMake,items.map(i=>i.carMake)]] as const).map(([label,value,setter,values])=><label key={label}>{label}<select value={value} onChange={e=>setter(e.target.value)}><option value="">All</option>{[...new Set(values)].filter(Boolean).map(v=><option key={v}>{v}</option>)}</select></label>)}<label>Availability<select value={availability} onChange={e=>setAvailability(e.target.value)}><option value="">All</option><option value="not_for_sale">Not for sale</option><option value="open_to_offers">Open to offers</option><option value="for_sale">For sale</option><option value="reserved">Reserved</option><option value="previously_owned">Previously owned</option></select></label></div></details>{filtered.length?<div className="collection-grid">{filtered.map(piece=><PieceCard piece={piece} key={piece.id} owner={owner}/>)}</div>:<div className="community-empty"><h2>{items.length?'No pieces match these filters':'A collection starts with one model'}</h2><p>{owner?'Add a model bought anywhere. You do not need an MCC purchase or a seller account.':'This collector has no public pieces in this view.'}</p>{owner&&<Link href="/collection?add=1" className="button dark">Add model</Link>}</div>}</>;
}
export function CollectionManager({items,shelves,visibility,handle,edit,add,seedCatalogId,selling,requestedAvailability,returnedListingId}:{items:Piece[];shelves:Shelf[];visibility:string;handle:string|null;edit:Piece|null;add:boolean;seedCatalogId?:string;selling:CollectionSellingOptions;requestedAvailability?:string;returnedListingId?:string}){const router=useRouter();return <><div className="community-title"><div><p className="eyebrow">Your physical pieces</p><h1>My Collection</h1><p>{items.filter(i=>i.availability!=='previously_owned').length} owned pieces · Purchases, wishlists and sale listings stay distinct.</p></div><div className="community-buttons"><Link className="button dark" href="/collection?add=1">Add model</Link>{handle&&<Link href={`/collectors/${handle}?visitor=1`}>View as visitor</Link>}<Link href="/profile?edit=1">Visibility & profile</Link></div></div>{(add||edit)&&<div className="composer"><h2>{edit?'Edit collection piece':'Add model'}</h2><CollectionPieceForm key={(edit?.id||'new')+':'+(edit?.version||0)} piece={edit} seedCatalogId={seedCatalogId} shelves={shelves} visibility={visibility} selling={selling} requestedAvailability={requestedAvailability} returnedListingId={returnedListingId}/><Link href="/collection">Close editor</Link></div>}<details className="shelf-create"><summary>Organize a shelf</summary><SubmitForm label="Create shelf" onSubmit={async f=>{await communityRequest({action:'shelf',name:f.get('name')});router.refresh();}}><label>Shelf name<input name="name" required maxLength={80} placeholder="Porsche road cars"/></label></SubmitForm></details>{!items.length&&<ContextualHelp id="first-collection" title="Add your first model" action={{href:"/collection?add=1",label:"Add your first model"}}><p>Keep a record of models you own, bought anywhere. Choose who can see each piece.</p><p className="contextual-help-example"><b>Example only:</b> Add your 1:64 model to a private shelf named “My collection.” This is a guide, not real collector activity.</p></ContextualHelp>}<CollectionGrid items={items} shelves={shelves} owner/></>;}
