"use client";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { preorderAction } from "./preorder-offer";
import { NumberField, Reason } from "./preorder-seller";
type AdminData={batches:Array<{id:string;title:string;store_name:string;evidence_state:string;evidence_reference:string;shortage:number;dispatch_end:string|null;status:string}>;sellers:Array<{id:string;store_name:string;status:string}>;exceptions:Array<{id:string;reservation_id:string;refund_status:string;error:string|null}>;notices:Array<{id:string;kind:string;attempts:number}>;policies:Array<{version:string;enabled:number;delay_response_days:number}>;consent:Array<{id:string;title:string;seller:string;reason:string;deadline:string}>;cancellations:Array<{reason:string;reservations:number;units:number;percent:number}>};
export function PreorderAdmin() {
  const [data,setData]=useState<AdminData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const load=useCallback(async()=>{const r=await fetch("/api/preorders?view=admin",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);},[]);
  useEffect(()=>{queueMicrotask(()=>void load().catch(e=>setError(e.message)));},[load]);
  async function submit(event:FormEvent<HTMLFormElement>,payload:Record<string,unknown>) {event.preventDefault();const d=Object.fromEntries(new FormData(event.currentTarget));setBusy(true);setError("");try{await preorderAction({...d,...payload,view:"admin",approved:d.approved==="on",enabled:d.enabled==="on",reviewed:d.reviewed==="on"});await load();setMessage("Review recorded.");}catch(e){setError(e instanceof Error?e.message:"Review failed.");}finally{setBusy(false);}}
  return <div className="preorder-dashboard"><p><Link href="/admin">Admin dashboard</Link> · Every override requires a reason and is recorded.</p>{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}
    <section className="preorder-panel"><h2>Launch policy</h2><p>Reservations remain disabled until the platform policy and delay response deadline have been reviewed for MCC. Published policy versions retain their deadlines.</p>
      <form className="preorder-form" onSubmit={e=>submit(e,{action:"policy"})}><NumberField name="delayResponseDays" label="Reviewed delay response deadline (calendar days)" initial={data?.policies[0]?.delay_response_days??7} min={1} max={30}/><label className="preorder-check"><input type="checkbox" name="reviewed" required/>Policy applicability, notices and response deadlines have been reviewed</label><label className="preorder-check"><input type="checkbox" name="enabled"/>Enable new reservations under this policy</label><Reason/><button className="button dark" disabled={busy}>Record policy review</button></form></section>
    <section className="preorder-panel"><h2>Seller eligibility</h2><form className="preorder-form" onSubmit={e=>submit(e,{action:"eligibility"})}><label>Professional store<select name="sellerId" required>{data?.sellers.map(s=><option key={s.id} value={s.id}>{s.store_name} ({s.status})</option>)}</select></label><label>Verified supply source (private)<input name="supplySource" required/></label><label className="preorder-check"><input type="checkbox" name="approved"/>Approve new preorder offers and reservations</label><Reason/><button className="button outline" disabled={busy}>Update eligibility</button></form><p>Disabling eligibility pauses new commitments and preserves existing fulfillment and refund access.</p></section>
    <section className="preorder-panel"><h2>Incoming allocation review</h2>{data?.batches.map(b=><div key={b.id} className="preorder-event"><h3>{b.title} · {b.store_name}</h3><p>{b.status} · Evidence: {b.evidence_state} · Shortage: {b.shortage} · Dispatch deadline: {b.dispatch_end??"Unknown"}</p><p>Private evidence reference: {b.evidence_reference||"Not supplied"}</p><form className="preorder-form" onSubmit={e=>submit(e,{action:"review_evidence",batchId:b.id})}><Reason/><button className="button outline" disabled={busy||!b.evidence_reference}>Record allocation evidence review</button></form></div>)}</section>
    <section className="preorder-panel"><h2>Refund and delivery exceptions</h2>{data?.exceptions.map(e=><p key={e.id}>Reservation {e.reservation_id} · Refund {e.refund_status} · {e.error}</p>)}<p>{data?.notices.length??0} transactional notices awaiting delivery.</p><form className="preorder-form" onSubmit={e=>submit(e,{action:"maintenance"})}><Reason/><button className="button outline" disabled={busy}>Run expiry, reminders and refund recovery</button></form></section>
    <section className="preorder-panel"><h2>Unresolved delay responses</h2>{data?.consent.length?data.consent.map(r=><p key={r.id}>{r.title} · {r.seller} · {r.reason.replaceAll("_"," ")} · Response due {r.deadline}</p>):<p>No outstanding responses.</p>}</section>
    <section className="preorder-panel"><h2>Cancellation causes</h2><p>Percentages are measured against all accepted reservations. Expired review holds are excluded.</p>{data?.cancellations.map(c=><p key={c.reason}>{c.reason.replaceAll("_"," ")} · {c.reservations} reservations / {c.units} units · {c.percent}%</p>)}</section>
  </div>;
}
