"use client";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { preorderAction } from "./preorder-offer";
import { NumberField, Reason } from "./preorder-seller";
type MaintenancePreview={checkedAt:string;expiring:number;reminders:number;dispatchNotices:number;notices:number;refundPayments:number;refundRequests:number;depositCheckouts:number;staleCheckouts:number;overdueBatches:number;allocations:number;restockWatches:number;retainedDeposits:number;lastRun:{created_at:string;detail:string}|null};
type AdminData={maintenance:MaintenancePreview;batches:Array<{id:string;title:string;terms:string;store_name:string;evidence_state:string;evidence_reference:string;shortage:number;dispatch_end:string|null;status:string}>;sellers:Array<{id:string;store_name:string;status:string}>;exceptions:Array<{id:string;reservation_id:string;refund_status:string;error:string|null}>;notices:Array<{id:string;kind:string;attempts:number}>;policies:Array<{version:string;enabled:number;delay_response_days:number}>;consent:Array<{id:string;title:string;seller:string;reason:string;deadline:string}>;cancellations:Array<{reason:string;reservations:number;units:number;percent:number}>};
export function PreorderAdmin() {
  const [data,setData]=useState<AdminData|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const [preview,setPreview]=useState<MaintenancePreview|null>(null);
  const [result,setResult]=useState<{expiry:{considered:number;remaining:number};reminders:{sent:number;considered:number};recovery:{before:number;remaining:number;pendingDeposits:number;pendingSettlements:number}}|null>(null);
  const load=useCallback(async()=>{const r=await fetch("/api/preorders?view=admin",{cache:"no-store"});const b=await r.json();if(!r.ok)throw new Error(b.error);setData(b);},[]);
  useEffect(()=>{queueMicrotask(()=>void load().catch(e=>setError(e.message)));},[load]);
  async function submit(event:FormEvent<HTMLFormElement>,payload:Record<string,unknown>) {event.preventDefault();const d=Object.fromEntries(new FormData(event.currentTarget));setBusy(true);setError("");try{const response=await preorderAction({...d,...payload,view:"admin",approved:d.approved==="on",enabled:d.enabled==="on",reviewed:d.reviewed==="on"});if(response.result){setResult(response.result);setPreview(null);}await load();setMessage(payload.action==="maintenance"?"Maintenance pass finished. Review each result and remaining exceptions below.":"Review recorded.");}catch(e){setError(e instanceof Error?e.message:"Review failed.");}finally{setBusy(false);}}
  return <div className="preorder-dashboard"><p><Link href="/admin">Admin dashboard</Link> · Every override requires a reason and is recorded.</p>{error&&<p role="alert" className="form-error">{error}</p>}{message&&<p role="status">{message}</p>}
    <section className="preorder-panel"><h2>Preorder listings</h2><p>Active stores create preorders from their listing form. Buyers pay a 10% deposit and the remaining balance when stock is ready.</p>{data?.batches.length ? data.batches.map(b=><p key={b.id}><strong>{b.title}</strong> · {b.store_name} · {b.status} · Expected ship date {b.dispatch_end?.slice(0,10) ?? "Not set"}{b.shortage > 0 && ` · ${b.shortage} units short`}</p>) : <p>No preorder listings yet.</p>}</section>
    {data?.batches.some(b=>JSON.parse(b.terms).paymentModel !== "deposit_10") && <details className="preorder-panel"><summary>Legacy free-reservation controls</summary>
    <section><h2>Legacy reservation policy</h2><p>These controls apply only to older free-reservation offers. New deposit preorders use the listing form and do not require these reviews.</p>
      <form className="preorder-form" onSubmit={e=>submit(e,{action:"policy"})}><NumberField name="delayResponseDays" label="Reviewed delay response deadline (calendar days)" initial={data?.policies[0]?.delay_response_days??7} min={1} max={30}/><label className="preorder-check"><input type="checkbox" name="reviewed" required/>Policy applicability, notices and response deadlines have been reviewed</label><label className="preorder-check"><input type="checkbox" name="enabled"/>Enable new reservations under this policy</label><Reason/><button className="button dark" disabled={busy}>Record policy review</button></form></section>
    <section className="preorder-panel"><h2>Seller eligibility</h2><form className="preorder-form" onSubmit={e=>submit(e,{action:"eligibility"})}><label>Professional store<select name="sellerId" required>{data?.sellers.map(s=><option key={s.id} value={s.id}>{s.store_name} ({s.status})</option>)}</select></label><label>Verified supply source (private)<input name="supplySource" required/></label><label className="preorder-check"><input type="checkbox" name="approved"/>Approve new preorder offers and reservations</label><Reason/><button className="button outline" disabled={busy}>Update eligibility</button></form><p>Disabling eligibility pauses new commitments and preserves existing fulfillment and refund access.</p></section>
    <section className="preorder-panel"><h2>Legacy allocation review</h2>{data?.batches.filter(b=>JSON.parse(b.terms).paymentModel !== "deposit_10").map(b=><div key={b.id} className="preorder-event"><h3>{b.title} · {b.store_name}</h3><p>{b.status} · Evidence: {b.evidence_state} · Shortage: {b.shortage} · Dispatch deadline: {b.dispatch_end??"Unknown"}</p><p>Private evidence reference: {b.evidence_reference||"Not supplied"}</p><form className="preorder-form" onSubmit={e=>submit(e,{action:"review_evidence",batchId:b.id})}><Reason/><button className="button outline" disabled={busy||!b.evidence_reference}>Record allocation evidence review</button></form></div>)}</section></details>}
    <section className="preorder-panel"><h2>Refund and delivery exceptions</h2>{data?.exceptions.map(e=><p key={e.id}>Reservation {e.reservation_id} · Refund {e.refund_status} · {e.error}</p>)}<p>{data?.notices.length??0} transactional notices awaiting delivery.</p><p>Last successful pass: {data?.maintenance.lastRun ? new Date(data.maintenance.lastRun.created_at.replace(" ","T")+ (data.maintenance.lastRun.created_at.includes("T") ? "" : "Z")).toLocaleString() : "Not recorded"}.</p><button className="button outline" disabled={busy || !data} onClick={async()=>{setBusy(true);setError("");try{const response=await fetch("/api/preorders?view=admin",{cache:"no-store"});const next=await response.json();if(!response.ok)throw new Error(next.error);setPreview(next.maintenance);}catch(e){setError(e instanceof Error?e.message:"Preview failed.");}finally{setBusy(false);}}}>Preview maintenance</button>
      {preview && <div className="preorder-event"><h3>Maintenance preview</h3><p>Checked {new Date(preview.checkedAt).toLocaleString()}. Eligibility is rechecked during the run; counts can change.</p><ul><li>Expiry: {preview.expiring} reservations; {preview.staleCheckouts} stale checkouts; {preview.overdueBatches} overdue batches requiring responses.</li><li>Communications: {preview.reminders} payment reminders; {preview.dispatchNotices} dispatch notices; {preview.notices} queued notices due for delivery; {preview.restockWatches} listing notification checks.</li><li>Financial recovery: {preview.refundPayments} payment refunds and {preview.refundRequests} order refund requests; {preview.depositCheckouts} deposit checkout checks; {preview.retainedDeposits} retained deposit settlements.</li><li>Allocation: {preview.allocations} batches to check for stock allocation. Expiry may queue additional refunds and notices in the same pass.</li></ul><form className="preorder-form" onSubmit={e=>submit(e,{action:"maintenance"})}><Reason/><button className="button outline" disabled={busy}>Run reviewed maintenance</button></form></div>}
      {result && <div role="status"><h3>Results by operation</h3><p>Expiry: {result.expiry.considered} considered; {result.expiry.remaining} still eligible.</p><p>Delivery: {result.reminders.sent} sent of {result.reminders.considered} considered.</p><p>Refund recovery: {result.recovery.before} pending before the pass; {result.recovery.remaining} remain. Deposit checks remaining: {result.recovery.pendingDeposits}. Settlements remaining: {result.recovery.pendingSettlements}. A completed pass does not mean every refund or delivery succeeded.</p></div>}</section>
    <section className="preorder-panel"><h2>Unresolved delay responses</h2>{data?.consent.length?data.consent.map(r=><p key={r.id}>{r.title} · {r.seller} · {r.reason.replaceAll("_"," ")} · Response due {r.deadline}</p>):<p>No outstanding responses.</p>}</section>
    <section className="preorder-panel"><h2>Cancellation causes</h2><p>Percentages are measured against all accepted reservations. Expired review holds are excluded.</p>{data?.cancellations.map(c=><p key={c.reason}>{c.reason.replaceAll("_"," ")} · {c.reservations} reservations / {c.units} units · {c.percent}%</p>)}</section>
  </div>;
}
