"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import type { StoreData } from "./store-dashboard";
import { formatMoney, formatUtcDateTime } from "@/lib/format";
import { ContextualHelp } from "./contextual-help";
import { trackEvent, sellerSetupElapsed } from "@/lib/analytics-client";
import { listingPhotoEvidence } from "@/lib/listing-evidence";
import "./seller-workflows.css";

export function SellerSetup({ data }: { data: StoreData }) {
  const { setup } = data;
  useEffect(() => {
    sellerSetupElapsed(data.store.id, true);
    trackEvent("seller_setup_started", {}, { onceKey: `setup-start-${data.store.id}` });
    for (const step of setup.steps) if (step.complete) trackEvent("seller_setup_step_completed", { step: step.id }, { onceKey: `setup-step-${data.store.id}-${step.id}` });
  }, [setup, data.store.id]);
  return <section className="store-panel seller-setup-banner"><p className="eyebrow">Your saved setup · {setup.completed} of 4 complete</p><h2>{setup.completed === 4 ? "Your store setup" : "Get your first models ready"}</h2><p>Progress comes from your saved store, payment connection, shipping options, and inventory. Leave and return whenever you need.</p><ol className="seller-setup-list">{setup.steps.map(step => <li key={step.id} className={step.complete ? "complete" : ""}><span className="seller-setup-status">{step.complete ? "Complete" : "To do"}</span><Link href={step.href}>{step.title}</Link><p>{step.detail}</p></li>)}</ol><div className="seller-workflow-actions"><Link className="button dark small" href="/store?view=inventory#inventory-upload">Go straight to uploading inventory</Link><Link href="/store?view=help">Need help getting your first models listed?</Link></div><p><b>Application:</b> {data.store.status === "applicant" ? "Awaiting review" : data.store.status === "suspended" ? "Sales suspended" : "Approved"}. <b>Listings:</b> {setup.listingCounts.draft} draft · {setup.listingCounts.pending} awaiting review · {setup.listingCounts.live} live. Application approval is separate from listing status.</p>{!setup.readyToPublish && <p>Drafts can be prepared now. Publishing requires all store details, a ready bank connection, shipping options, an active store, current <Link href="/store?view=settings#seller-terms">Seller Terms</Link>, and the listing’s required photos and details.</p>}</section>;
}

export function SellerNextActions({ data }: { data: StoreData }) {
  const orders = data.orders.filter(order => ["paid", "partially_refunded"].includes(order.paymentStatus) && ["unfulfilled", "processing"].includes(order.fulfillmentStatus));
  const attention = data.inventory.filter(product => ["draft", "pending_review", "rejected"].includes(product.status) || (product.availabilityType !== "preorder" && !listingPhotoEvidence(product, product.images).complete));
  const failed = data.orders.filter(order => order.sellerTransferStatus === "failed");
  return <section className="store-panel"><p className="eyebrow">Next actions</p><h2>Keep your store moving</h2><div className="seller-next-actions">{orders.slice(0, 4).map(order => <Link href={`/store?view=orders#order-${order.id}`} key={order.id}>Ship order {order.orderNumber}{order.shipByAt ? ` — by ${formatUtcDateTime(order.shipByAt)}` : " — check dispatch details"}</Link>)}{attention.slice(0, 3).map(product => <Link href={`/store?view=inventory&edit=${product.id}`} key={product.id}>{product.status === "pending_review" ? "Review submitted listing" : "Complete listing"}: {product.title}</Link>)}{failed.map(order => <Link href={`/store?view=payments#payment-${order.id}`} key={order.id}>Check payment release for {order.orderNumber}</Link>)}{!orders.length && !attention.length && !failed.length && <p>No orders or listings need action right now. <Link href="/store?view=inventory">Add or update inventory</Link>.</p>}</div></section>;
}

export function SellerPayments({ data, action }: { data: StoreData; action: (payload: Record<string, unknown>, options?: { reload?: boolean; message?: string }) => Promise<Record<string, unknown>> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function connect(refresh: boolean) {
    setBusy(true); setError("");
    try { const result = await action({ action: refresh ? "refresh_payments" : "connect_payments" }, { reload: refresh, message: refresh ? "Payment connection checked." : "Opening secure payment setup." }); if (typeof result.onboardingUrl === "string") window.location.assign(result.onboardingUrl); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "We could not open payment setup. Try again."); }
    finally { setBusy(false); }
  }
  return <div className="store-stack"><header className="store-page-heading"><div><p className="eyebrow">Money from your sales</p><h2>Payments</h2><p>See your payment connection and the release status of each order.</p></div></header><section className="store-panel"><h3>Connect your bank account to receive payments</h3><p>{data.setup.steps.find(step => step.id === "payments")?.complete ? "Your connection is ready to accept payments and receive proceeds." : "Provide your identity and bank details securely with Stripe, then return here and check the connection."}</p><p>Bank details stay with Stripe. A payment account check is separate from Model Car Center’s store approval.</p><div className="seller-workflow-actions"><button className="button dark small" disabled={busy || data.store.status === "suspended" || !data.setup.termsAccepted} onClick={() => void connect(false)}>{busy ? "Please wait…" : "Open secure bank setup"}</button><button className="button outline small" disabled={busy || data.store.status === "suspended"} onClick={() => void connect(true)}>Check connection</button></div>{!data.setup.termsAccepted && <p><Link href="/store?view=settings#seller-terms">Accept the current Seller Terms</Link> to start bank setup.</p>}{error && <p className="form-error" role="alert">{error}</p>}</section><section className="store-panel"><h3>Your payout timeline</h3><ol><li>Buyer pays: proceeds are held while you prepare and ship the order.</li><li>Carrier confirms delivery: the order’s protection window runs before proceeds become eligible.</li><li>Release: no open case, final processing fee available, and payment connection ready.</li><li>Bank arrival: Stripe’s payout schedule applies after release; this is later than the release date.</li></ol><p>Open cases, refunds, missing tracking, and payment-account issues can delay or reduce release. Review the actual dates for each order.</p></section><section className="store-panel"><div className="hub-payouts"><div><span>Released to payment account</span><b>{formatMoney(data.hub.releasedCents)}</b></div><div><span>Held proceeds</span><b>{formatMoney(data.hub.heldCents)}</b></div></div>{data.hub.pendingFeeOrders > 0 && <p>{data.hub.pendingFeeOrders} additional orders await final processing fees.</p>}{data.orders.length ? data.orders.map(order => <article id={`payment-${order.id}`} key={order.id}><h3>{order.orderNumber}</h3><p>{order.sellerTransferStatus.replaceAll("_", " ")} · {order.sellerProceedsCents === null ? "Final proceeds pending" : formatMoney(order.sellerProceedsCents)}</p><p>{order.payoutEligibleAt ? `Eligible no earlier than ${formatUtcDateTime(order.payoutEligibleAt)}, subject to holds.` : "Eligibility is confirmed after delivery."}</p><Link href={`/store?view=orders&filter=all#order-${order.id}`}>View order and fees</Link></article>) : <p>Payments will appear after your first order.</p>}</section></div>;
}

export function SellerHelp() {
  return <section className="store-panel seller-help"><p className="eyebrow">Short task guides</p><h2>Seller help</h2><h3>Need help getting your first models listed?</h3><p><Link href="/contact#seller-setup-help">Contact setup support</Link> with your store name and the step where you are stuck. You can ask about a short setup session; availability is confirmed by the owner.</p><h3>Add models</h3><p><Link href="/store?view=inventory&edit=new">Add one model</Link>, or <Link href="/store?view=inventory#inventory-upload">upload inventory from a spreadsheet</Link>. New inventory is saved as drafts. Add actual-item photos, verify condition details, and complete setup before publishing.</p><h3>Sold somewhere else?</h3><p>Stock is not automatically synchronized with Shopify, eBay, or other websites. Open Inventory and use Update stock &amp; price to reduce the quantity immediately. For many changes, upload the same stable seller SKUs. Existing reservations cannot be removed by lowering stock.</p><h3>Your first order</h3><p>Open Orders to ship and check the ship-by deadline. Protect the model, accessories, and original packaging inside a sturdy outer shipping box. Create a label when carrier tools are available, or buy postage separately and add the carrier and tracking number.</p><h3>Getting paid</h3><p>Open Payments to connect your bank account and see held and released proceeds. Release eligibility follows delivery and the order’s protection terms; open cases pause release. Bank arrival follows Stripe’s schedule.</p><ContextualHelp id="seller-inventory" title="Have a spreadsheet? Add multiple models at once"><p>Use the template in <Link href="/store?view=inventory#inventory-upload">Upload inventory from a spreadsheet</Link>. Keep seller SKUs unchanged when updating stock. This hint stays available here.</p></ContextualHelp></section>;
}
