"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import type { StoreData } from "./store-dashboard";
import { PromotedListingsPanel } from "./promoted-listings-panel";
import { SellerSetup, SellerNextActions, SellerThumbnail } from "./seller-setup";
import { availableUnits, type HubNavigate } from "@/lib/seller-hub";
import { salesRanges, sellerSalesReport } from "@/lib/seller-dashboard";
import { formatMoney, formatUtcDate } from "@/lib/format";

type Props = { data: StoreData; navigate: HubNavigate };
function Metric({ label, value, note, href }: { label: string; value: ReactNode; note: string; href: string }) {
  return <Link className="seller-metric" href={href}><span>{label}</span><strong>{value}</strong><small>{note} →</small></Link>;
}

export function HubOverview({ data, navigate }: Props) {
  return <div className="store-stack"><header className="store-page-heading"><div><h2>Overview</h2><p>Your next orders and store activity.</p></div><button className="button dark small" disabled={data.store.status === "suspended"} onClick={() => navigate("inventory", "all", "new")}>Add model</button></header>
    <SellerNextActions data={data}/>
    <div className="seller-summary-metrics"><Metric label="Paid orders" value={data.analytics.paidOrders} note="Order history" href="/store?view=orders&filter=all"/><Metric label="Released to Stripe" value={formatMoney(data.hub.releasedCents)} note="MCC releases, less reversals" href="/store?view=payments"/><Metric label="Live listings" value={data.analytics.activeListings} note="Manage inventory" href="/store?view=inventory"/><Metric label="Collectors watching" value={data.demand.savedBuyers} note="See buyer interest" href="/store?view=growth"/></div>
    <div className="seller-task-links"><Link href="/store?view=messages">Buyer messages →</Link><Link href="/store?view=analytics">Sales trends →</Link><Link href="/store?view=inventory&filter=low">Review low stock →</Link></div>
    <SellerSetup data={data}/>
  </div>;
}

const growthViews = [["saved", "Buyer interest"], ["wants", "Model Hunts"], ["trending", "Rising interest"], ["unfulfilled", "Restock demand"], ["pricing", "Pricing"], ["promoted", "Promoted listings"]] as const;
export function HubGrowth({ data, navigate, filter }: Props & { filter?: string }) {
  const selected = growthViews.some(([key]) => key === filter) ? filter : "saved";
  const rows = data.demand.products.filter(row => selected === "trending" ? row.trending : selected === "unfulfilled" ? row.restockSubscribers > 0 && data.inventory.some(product => product.id === row.productId && availableUnits(product) === 0) : row.saves > 0);
  const wants = selected === "unfulfilled" ? data.demand.wants.filter(want => !want.productIds.some(id => data.inventory.some(product => product.id === id && product.status === "active" && product.availabilityType !== "preorder" && availableUnits(product) > 0))) : data.demand.wants;
  return <div className="store-stack"><header className="store-page-heading"><div><h2>Growth</h2><p>Buyer interest and tools you can use today.</p></div><label className="seller-control">Growth tool<select value={selected} onChange={event => navigate("growth", event.target.value)}>{growthViews.map(([key, label]) => <option value={key} key={key}>{label}</option>)}</select></label></header>
    {selected === "promoted" ? <PromotedListingsPanel/> : selected === "pricing" ? <section className="store-panel"><h3>Review your pricing</h3><p>{data.hub.slowIds.length} active listings have stock and no paid sale in 90 days. Review their photos, price, and buyer interest.</p><div className="seller-inline-actions"><Link className="button dark small" href="/store?view=inventory&filter=slow">Review slow stock</Link><Link href="/store?view=inventory&filter=bulk">Update stock & price</Link></div><p>Price changes affect future purchases. Targeted offers and scheduled discounts are not available.</p></section> : <>
      {selected !== "wants" && <section className="store-panel"><h3>{selected === "trending" ? "Rising wishlist interest" : selected === "unfulfilled" ? "Collectors waiting for stock" : "Listings collectors saved"}</h3><p>{selected === "trending" ? "At least 3 saves in the last 30 days, exceeding the previous 30 days." : selected === "unfulfilled" ? "Restock alerts for your unavailable listings." : "Current saves, excluding your own. Compare the last 30 days with the previous 30."}</p>
        {rows.length ? <div className="seller-growth-list">{rows.map(row => { const product = data.inventory.find(item => item.id === row.productId); return product ? <article key={row.productId}><SellerThumbnail src={product.primaryImageUrl} title={product.title}/><div><h4>{product.title}</h4><p>{product.scale} · SKU {product.sellerSku}</p><p>{row.saves} saves · {row.recent} recent / {row.previous} previous · {row.restockSubscribers} restock alerts</p><button className="text-button" disabled={data.store.status === "suspended"} onClick={() => navigate("inventory", "all", row.productId)}>Review listing →</button></div></article> : null; })}</div> : <p>{selected === "trending" ? "No listings meet the trend threshold yet." : selected === "unfulfilled" ? "No active restock requests for unavailable listings." : "Buyer interest appears when collectors save your listings."}</p>}
      </section>}
      {(selected === "wants" || selected === "unfulfilled") && <section className="store-panel"><h3>Model Hunts</h3><p>Open marketplace requests, grouped by preferences and budget. Buyer contact details stay private.</p>{wants.length ? <div className="seller-wants-list">{wants.map((want, index) => <article key={index}><h4>{want.vehicleMake} {want.vehicleModel}</h4><p>{[want.preferredScale, want.modelManufacturer, want.color, want.conditionPreference].filter(Boolean).join(" · ")}</p><p>{want.requests} requests · Budget {want.maxBudgetCents === null ? "not specified" : formatMoney(want.maxBudgetCents)}</p>{want.productIds.length ? <div className="seller-inline-actions">{want.productIds.map(id => <button className="text-button" key={id} disabled={data.store.status === "suspended"} onClick={() => navigate("inventory", "all", id)}>Review {data.inventory.find(product => product.id === id)?.sellerSku} →</button>)}</div> : <Link href="/store?view=inventory&edit=new">Add a matching model →</Link>}</article>)}</div> : <p>No Model Hunts match this view.</p>}</section>}
    </>}
    <details className="seller-growth-notes"><summary>About demand and upcoming tools</summary><p>Wishlist saves indicate interest, not a commitment to buy. Seller-level buyer search reports, store followers, targeted offers, and campaigns are not available. Share your <Link href={`/sellers/${data.store.slug}`}>storefront</Link> or use the available tools above.</p></details>
  </div>;
}

function change(current: number, previous: number, money = false, currency = "usd") {
  if (!previous) return current ? `Up from ${money ? formatMoney(0, currency) : "0"} previously` : "No change from previous period";
  const percent = (current - previous) / previous * 100;
  return `${percent > 0 ? "+" : ""}${percent.toFixed(1)}% vs previous period`;
}
export function HubAnalytics({ data, navigate }: Props) {
  const [days, setDays] = useState("30"), [currency, setCurrency] = useState("usd");
  const report = sellerSalesReport(data.orders, Number(days), new Date(data.asOf), currency);
  const currencies = [...new Set(["usd", ...data.orders.map(order => order.currency.toLowerCase())])];
  const max = Math.max(1, ...report.buckets.map(bucket => bucket.revenueCents));
  return <div className="store-stack"><header className="store-page-heading"><div><h2>Analytics</h2><p>One date range for sales, orders, units, and product performance.</p></div><div className="seller-inline-actions"><label className="seller-control">Date range<select value={days} onChange={event => setDays(event.target.value)}>{salesRanges.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{currencies.length > 1 && <label className="seller-control">Currency<select value={currency} onChange={event => setCurrency(event.target.value)}>{currencies.map(value => <option value={value} key={value}>{value.toUpperCase()}</option>)}</select></label>}</div></header>
    <p className="seller-period">{formatUtcDate(report.start)} – {formatUtcDate(report.end)} (UTC), compared with the preceding {days} days.</p>
    <div className="seller-summary-metrics seller-sales-metrics"><Metric label="Gross item sales" value={formatMoney(report.current.revenueCents, currency)} note={change(report.current.revenueCents, report.previous.revenueCents, true, currency)} href="/store?view=orders&filter=all"/><Metric label="Paid orders" value={report.current.orders} note={change(report.current.orders, report.previous.orders)} href="/store?view=orders&filter=all"/><Metric label={report.current.missingItems ? "Recorded units" : "Units sold"} value={report.current.missingItems === report.current.orders && report.current.orders ? "Unavailable" : report.current.units} note={report.current.missingItems || report.previous.missingItems ? "Item history incomplete; comparison unavailable" : change(report.current.units, report.previous.units)} href="#product-performance"/></div>
    {report.current.missingItems > 0 && <div className="seller-data-note" role="status"><strong>{report.current.missingItems} paid {report.current.missingItems === 1 ? "order has" : "orders have"} no item records.</strong><p>Revenue uses the recorded order subtotal. Units and product performance only include recorded items; missing items do not mean zero sales.</p><div className="seller-inline-actions">{report.missingOrderIds.map(id => <Link key={id} href={`/store?view=orders&filter=all#order-${id}`}>Review {data.orders.find(order => order.id === id)?.orderNumber} →</Link>)}</div></div>}
    {report.previous.missingItems > 0 && <p className="seller-data-note">{report.previous.missingItems} orders in the previous period lack item records. Product comparisons only cover recorded items.</p>}
    <section className="store-panel"><h3>Revenue over time</h3><p>Gross item sales in {currency.toUpperCase()}, before fees and refunds. Paid date is used when recorded.</p><div className="seller-revenue-chart" role="img" aria-label={`Gross item sales of ${formatMoney(report.current.revenueCents, currency)} over the selected ${days} days. Exact values follow.`}>{report.buckets.map(bucket => <div key={bucket.from}><div className="seller-chart-track"><span style={{ height: `${bucket.revenueCents / max * 100}%` }}/></div><small>{formatUtcDate(bucket.to).replace(/, \d{4}$/, "")}</small></div>)}</div><details><summary>Revenue values by interval</summary><dl className="seller-chart-values">{report.buckets.map(bucket => <div key={bucket.from}><dt>{formatUtcDate(bucket.from)} – {formatUtcDate(bucket.to)}</dt><dd className="seller-money">{formatMoney(bucket.revenueCents, currency)}</dd></div>)}</dl></details></section>
    <section className="store-panel" id="product-performance"><h3>Product performance</h3><p>Same {days}-day period. Review changes to decide which listings need attention.</p>{report.products.length ? <div className="seller-growth-list">{report.products.map(row => <article key={row.id ?? row.title}><SellerThumbnail src={row.image} title={row.title}/><div><h4>{row.title}</h4><p>{row.units} units · <b className="seller-money">{formatMoney(row.revenueCents, currency)}</b></p><p>{change(row.revenueCents, row.previousRevenueCents, true, currency)}</p>{row.id && data.inventory.some(product => product.id === row.id) ? <button className="text-button" onClick={() => navigate("inventory", "all", row.id!)}>Review listing →</button> : <span>Listing no longer available</span>}</div></article>)}</div> : <p>{report.current.missingItems ? "Product performance is unavailable until the missing order items are resolved." : "No recorded item sales in this period or the previous period."}</p>}</section>
    <details className="store-panel"><summary>Sales definitions and other reports</summary><p>Paid and partially refunded orders are included. Unpaid, fully refunded, and marked test orders are excluded. Partial refunds are not deducted from gross sales or recorded units. Comparisons use equally long periods ending at this page’s last load.</p>{report.excludedTestOrders > 0 && <p>{report.excludedTestOrders} marked test orders excluded.</p>}<div className="seller-inline-actions"><Link href="/store?view=payments">Payment releases and holds →</Link><Link href="/store?view=inventory&filter=slow">Review slow stock →</Link></div></details>
  </div>;
}
